apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-watcher-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-watcher-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-watcher-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: cm-watcher-sa
    namespace: default
roleRef:
  kind: Role
  name: cm-watcher-role
  apiGroup: rbac.authorization.k8s.io