apiVersion: v1
kind: Secret
metadata:
  name: watched-secret
  namespace: default
type: Opaque
data:
  DB_PASSWORD: {{ .Values.dbPassword | b64enc | quote }}
  API_KEY: {{ .Values.apiKey | b64enc | quote }}